use gpui::actions;

actions!(
    pdf_editor,
    [
        OpenDocument,
        SaveDocument,
        NextPage,
        PreviousPage,
        SelectTool,
        HandTool,
        HighlightTool,
        UnderlineTool,
        StrikeoutTool,
        AddTextTool,
        NoteTool,
        ShapeTool,
        RedactTool,
        ZoomIn,
        ZoomOut,
        ActualSize,
        FitPage,
        CommitText,
        CommitNote,
        CopySelection,
        Search,
        NextSearchResult,
        PreviousSearchResult
    ]
);
