use gpui::actions;

actions!(
    pdf_editor,
    [
        OpenDocument,
        SaveDocument,
        SaveDocumentAs,
        NextPage,
        PreviousPage,
        FirstPage,
        LastPage,
        GoToPage,
        SelectTool,
        EditTool,
        HandTool,
        HighlightTool,
        UnderlineTool,
        StrikeoutTool,
        AddTextTool,
        NoteTool,
        SignatureTool,
        ShapeTool,
        RedactTool,
        ZoomIn,
        ZoomOut,
        ActualSize,
        FitPage,
        FitWidth,
        Undo,
        Redo,
        Cancel,
        SelectAllText,
        CopySelection,
        Search,
        NextSearchResult,
        PreviousSearchResult
    ]
);
