[package]
name = "ui"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
async-channel.workspace = true
chrono.workspace = true
document-core = { path = "../document-core" }
gpui.workspace = true
gpui-component.workspace = true
image.workspace = true
pdf-engine = { path = "../pdf-engine" }

[lints]
workspace = true
